##########
# collectionbuilder-gh
# FPJ Productions • Digital Collection (GitHub Pages)
##########

##########
# URL VARIABLES
# If using GitHub Pages user/org site:
#   url: https://<username>.github.io
#   baseurl: ""   (empty)
# If using a project site:
#   url: https://<username>.github.io
#   baseurl: /<repo-name>
#
url: https://fpjproductions.github.io
baseurl: /fpj-collection

# Repo link (optional but nice to have)
source-code: https://github.com/fpjproductions/fpj-collection

##########
# SITE SETTINGS
title: FPJ Film Posters & Stills
tagline: Restored classics, artifacts, and behind-the-scenes history
description: "A browsable digital collection of Fernando Poe Jr. posters, lobby cards, stills, and restoration notes curated by FPJ Productions."
author: FPJ Productions

##########
# COLLECTION SETTINGS
# CSV filename (without .csv) inside _data/
metadata: fpj-metadata

##########
# BRANDING (optional)
organization-name: "FPJ Productions"
organization-link: https://www.youtube.com/@fpjproductions
# Replace with your hosted logos (PNG/SVG). You can drop these into /assets/img/ and reference relative paths:
organization-logo-banner: /assets/img/fpj-banner-logo.png
organization-logo-nav: /assets/img/fpj-nav-logo.png

##########
# ROBOTS (set to true to hide from search engines while drafting)
# noindex: true

##########
# BUILD SETTINGS
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
sass:
  style: compressed
